---
user_name: galaxy
user_group_name: galaxy

# create_user task
handy_groups:
  - group_name: "{{ user_group_name }}"
    group_gid: 2411

handy_users:
  - user_name: "{{ user_name }}"
    user_uid: 881567
    user_comment: Galaxy service
    user_group: "{{ user_group_name }}"

galaxy_user:
  name: "{{ user_name }}"
__galaxy_user_group: "{{ user_group_name }}"
galaxy_root: /opt/galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.yml"

# Autofs
autofs_service.install: true
autofs_service.enable: true
nfs_kernel_tuning: true

autofs_mount_points:
  - data
  - usrlocal

autofs_conf_files:
  data:
    - share       -rw,hard,nosuid,nfs,nfsvers=4,minorversion=2         {{ groups['nfs_dev'][0] }}:/data/share
  usrlocal:
    - /opt/galaxy        -rw,hard,nosuid,nfs,nfsvers=4,minorversion=2         {{ groups['nfs_dev'][0] }}:/opt/galaxy

# SystemD
# IT currently has a smaller VM for celery (eu is 16 cores 32 gb ram). We reduce the number of max tasks and internal workers.
galaxy_systemd_mode: ""
galaxy_systemd_celery: true
galaxy_systemd_celery_internal_max_tasks: 50
galaxy_systemd_celery_beat_schedule_path: "/opt/galaxy/celery/celery-beat-schedule"
galaxy_systemd_watchdog: true

galaxy_systemd_celery_internal_workers: 10
galaxy_systemd_celery_external_workers: 2

# Flower
flower_custom_logging: false
flower_install: false
flower_app_dir: /opt/galaxy
flower_python_path: server/lib
flower_galaxy_conf: "{{ galaxy_config_file }}"
flower_venv_dir: /opt/galaxy/venv
flower_app_name: galaxy.celery

flower_persistent: true

flower_broker_api: "https://flower:{{ rabbitmq_users_password.flower }}@{{ rabbitmq_url }}/api/"
flower_broker_url: "amqp://flower:{{ rabbitmq_users_password.flower }}@{{ rabbitmq_url }}:5671/galaxy?ssl=true"

tailscale_authkey: "{{ tailacale_auth_key_usegalaxy_it }}" # FIXME tailscale is not installed.

# RabbitMQ
rabbitmq_url: "{{ groups['rabbitmq'][0] }}"

# Redis
redis_connection_string: "redis://:{{ redis_requirepass }}@{{ rabbitmq_url }}:6379/0"
