private_token: {{ pulsar_private_token }}
persistence_directory: {{ galaxy_nfs_location }}/persisted_data
staging_directory: {{ galaxy_nfs_location }}/staging
tool_dependency_dir: {{ galaxy_nfs_location }}/tools/

managers:
  _default_:
    type: queued_condor
